### ISSUE TITLE
[gametests] Infinite loop on `regolith install`

### ISSUE THREAD

**Issue by Nusiq** [Bedrock-OSS/regolith-filters#36]
`regolith install` causes Regolith to get stuck in infinite loop probably due to a bad npm module setup.

# Related issues
- Regolith project: https://github.com/Bedrock-OSS/regolith/issues/174
- Npm project: https://github.com/npm/npm/issues/18477

# Video
https://user-images.githubusercontent.com/34062025/174442211-b7741813-4265-4f2b-9c2a-037335f6bf09.mp4

**Comment by stirante** [comment]
Fixed by #38
