### ISSUE TITLE
[gametests] `debug_build` js.map is not created in `.regolith/tmp` directory

### ISSUE THREAD

**Issue by bogumidu** [Bedrock-OSS/regolith-filters#54]
## Expected output:
 File `scripts.js.map` is created in `.regolith/tmp` directory before being copied to the export target.

## Current state:
 File `scripts.js.map` is only present in export target instead of both directories.

## Reasoning:
 This makes using minecraft-js debugger significantly more difficult.

## Current workaround:
 Downgrading gametests to version 1.6.0 fixes the issue

**Comment by stirante** [comment]
Refer to the changelog
https://github.com/Bedrock-OSS/regolith-filters/tree/master/gametests#161

`debug_build` was renamed to `debugBuild` to keep the same naming.
